"""Añade imagen al modelo post

Revision ID: 839fdff5f55c
Revises: 61667c249cb7
Create Date: 2023-06-04 15:19:21.918834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839fdff5f55c'
down_revision = '61667c249cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_name', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image_name')

    # ### end Alembic commands ###
